name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Validations
      uses: yarn lint

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test